# Generated by Django 5.1.4 on 2024-12-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secure_file_share", "0002_rename_file_file_file_blob"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlist",
            name="otp",
            field=models.IntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
