# Generated by Django 5.1.4 on 2024-12-29 13:14

import secure_file_share.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secure_file_share", "0003_userlist_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_username", models.CharField(max_length=100)),
                ("from_username", models.CharField(max_length=100)),
                ("to_email", models.EmailField(max_length=254)),
                ("from_email", models.EmailField(max_length=254)),
                ("file_id", models.IntegerField()),
                ("filename", models.CharField(max_length=255)),
                ("permission_type", models.TextField(default="View")),
                ("file_blob", models.BinaryField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "expiry_time",
                    models.DateTimeField(
                        default=secure_file_share.models.default_expiry_time
                    ),
                ),
                ("shared_link", models.URLField()),
            ],
        ),
    ]
